testing/testing/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testoff.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testing/testoff/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.image_upload_view)
]

testing/testoff/models.py
from django.db import models

class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title

testing/testoff/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Image
        fields = ('title', 'image')

testing/testoff/views.py
from django.shortcuts import render
from .forms import ImageForm
import numpy as np
import tensorflow as tf
import keras.utils as image
import cv2

def prepare(filepath):
    IMG_SIZE = 48
    img_array = cv2.imread(filepath)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    new_array = new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)
    new_array = new_array.astype("float") / 255.0
    return new_array

def image_upload_view(request):
    """Process images uploaded by users"""
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get the current instance object to display in the template
            img_obj = form.instance
            asd = str(request.FILES)[51:-16]

            model = tf.keras.models.load_model('./models/emotion_detection.h5')
            #img = image.load_img("./media/images/" + asd, target_size=(48, 48), color_mode="rgb")
            CATEGORIES = ['angry', 'disgusted', 'fearful', 'happy', 'neutral', 'sad', 'surprised']
            prediction = model.predict([prepare("./media/images/" + asd)])
            prediction  # will be a list in a list.
            score = tf.nn.softmax(prediction[0])
            answer = "This image most likely belongs to {} with a {:.2f} percent confidence.".format(CATEGORIES[np.argmax(score)], 100 * np.max(score))
            #return render(request, 'index.html', {'form': form, 'img_obj': img_obj})
            return render(request, 'index.html', {'form': form, 'img_obj': img_obj, 'answer': answer})
    else:
        form = ImageForm()
    return render(request, 'index.html', {'form': form})

testing/testoff/templates/index copy.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="main.css">
</head>
<body>

<header>
<div class="main-heading">
  <h1><span>Emotion detector</span></h1>
  <p>Upload a photo and we will recognize an emotion on it</p>
</div>
</header>

  <form method="post" enctype="multipart/form-data">
    <button class="bot1" type="submit">Upload</button>
  </form>
  <!-- <h3>Succesfully uploaded :</h3> -->
    <img src="" alt="connect..." style="text-align: center; height:300px; width: 300px; margin: auto;">
    <div>
        <div>
            <p><output>{{answer}}</output></p>
        </div>
    </div>
</body>
</html>

testing/testoff/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head>
<body>
<header>
  <div class="main-heading">
    <h1><span>Emotion detector</span></h1>
    <p>Upload a photo and we will recognize an emotion on it</p>
  </div>
  </header>
</header>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><label for="id_title">   </label><div class="input-wrapper"><input placeholder="Come up with a picture name" type="text" name="title" maxlength="200" required id="id_title"></div></p>
    <p><label for="id_image"></label><div><input title="Browse..." class="input-file" type="file" name="image" accept="image/*" id="id_image"></div></p>
    <button class="bot1" type="submit">Upload</button>
  </form>
  {% if img_obj %}
<div class="uploaded">
  <h3 class="uploaded-text">Succesfully uploaded : {{img_obj.title}}</h3>
    <div style="padding-left:40%">
    <img src="{{ img_obj.image.url}}" alt="connect" class="foto-demonstration" style="height:300px; width: 300px; margin-left: auto; margin-right: auto;">
  </div>
        {% endif %}
<div>
        {% if answer %}
        <div>
            <p class="uploaded-text"><output>{{answer}}</output></p>
        </div>
        {% endif%}
    </div>
    </div>
</body>
</html>